### ISSUE TITLE
IPN on Sandbox Mode

### ISSUE THREAD

**Issue by didi3r** [claudiosmweb/woocommerce-mercadopago#10]
IPN notifications don't work if the sandbox mode is active. Testing on this URL:
https://www.mercadopago.com/mla/herramientas/notificaciones

It will throw you the following error:
 {"protocolVersion":{"major":1,"minor":1,"protocol":"HTTP"},"reasonPhrase":"Internal Server Error","statusCode":500}

This only happends when the sandbox mode is active.

**Comment by claudiosmweb** [comment]
I'll check it.

**Comment by claudiosmweb** [comment]
Working fine with our master branch (3.0.0-beta-1).
We'll have a new release soon.
