### ISSUE TITLE
Sandbox don't work

### ISSUE THREAD

**Issue by matiasmasca** [claudiosmweb/woocommerce-mercadopago#13]
Hi,
I am using WooCommerce v2.5.2 with WooCommerce MercadoPago version 2.0.1 and looks like something change at MercadoPago becouse I can't run any more the "Sandbox mode" for my test shop. I received the message in the pop-up:
"Ups, algo funcionó mal
Cierra e intenta nuevamente."
 
"Something was wrong. Close and try again"

Any idea?

**Comment by claudiosmweb** [comment]
I just tested and seems to be working fine now.
