### ISSUE TITLE
Woocommerce IPN problem / order status still on "pending"

### ISSUE THREAD

**Issue by latiendadelfanatico** [claudiosmweb/woocommerce-mercadopago#14]
Hi Claudio,

We use your plug-in whitin our site and it worked perfectly with woocommerce 2.3.13. 

However, when we updated to woocommerce to 2.4, it stopped receiving IPN from MercadoPago, so the site doesn't refresh the order status neither reduce inventory.

Do you thing this is a compatibility issue?

Thanks for your help. We are very willing to do a good donation! please send us your details!

**Comment by claudiosmweb** [comment]
Don't have any compatibility issue.
When it happens... It's your server blocking MercadoPago IPN using ModSecurity, or a security plugin or CloudFlare.
