### ISSUE TITLE
Shouldn't 'sslverify' be set to true?

### ISSUE THREAD

**Issue by juanfraa** [claudiosmweb/woocommerce-mercadopago#6]
Hey Claudio,

I hope you're doing well.

`get_mercadopago_url()` sets `sslverify` to `false`, which is a security vulnerability. the certificate must be verified in order to make sure the connection is secure.

Is there any reason why you are setting that to false? Let me know and I can send you a PR with the changes.

Cheers,
Juan

**Comment by claudiosmweb** [comment]
Do you not trust the certificate of MercadoPago API?
The request is always the same API, URL does not change and in this way is more faster the request.
Why that would be a "security vulnerability"?
If MercadoPago API stop being trust tomorrow, SSL will be the last of your problem.
