### ISSUE TITLE
Add optional expiration to preferences

### ISSUE THREAD

**Issue by einacio** [claudiosmweb/woocommerce-mercadopago#7]
By default, preferences are available to pay for up to 30 days, but sometimes a product or offer may be only available for a more limited time period. It would be useful to be able to set a max number of days per product/variation or at least storewide, using the `expiration_date_from` and `expiration_date_to` atributtes of the preference.

**Comment by claudiosmweb** [comment]
Use the `woocommerce_mercadopago_args` filter for it.
